# Generated by Django 4.0.2 on 2022-03-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_parent_id_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/% Y/% m/% d/', verbose_name='Image'),
        ),
    ]
