# Generated by Django 4.0.2 on 2022-02-21 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_discount_alter_product_options_category_parent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='This is deleted datetime', null=True, verbose_name='Deleted Datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('type', models.CharField(choices=[('price', 'price'), ('percent', 'percent')], max_length=10)),
                ('value', models.PositiveIntegerField()),
                ('max_price', models.PositiveIntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['-last_updated'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='product/img', verbose_name='Image'),
        ),
    ]
