# Generated by Django 4.0.2 on 2022-02-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_offcode_alter_discount_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Product'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
