# Generated by Django 4.0.2 on 2022-03-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_category_slug'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='OrderItem',
        ),
    ]
