# Generated by Django 4.0.2 on 2022-03-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_address_is_default'),
        ('order', '0002_rename_basket_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offcode',
            old_name='code',
            new_name='verify_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='final_price',
        ),
        migrations.AddField(
            model_name='order',
            name='owner_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='off_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
